import { ChestItemModel } from "./chest.model";

export const CHEST_ITEM_LIST: ChestItemModel[] = [
    { 
      id: crypto.randomUUID(),
      name: 'Sword of Destiny',
      description: 'A legendary sword with immense power.',
      type: 'weapon',
      quantity: 1,
      equipped: false,
    },
    {
      id: crypto.randomUUID(),
      name: 'Healing Potion',
      description: 'Restores a significant amount of health.',
      type: 'consumable',
      quantity: 5,
      equipped: false,
    },
    {
      id: crypto.randomUUID(),
      name: 'Shield of Valor',
      description: 'A sturdy shield that can block powerful attacks.',
      type: 'armor',
      quantity: 1,
      equipped: false,
    },
    {
      id: crypto.randomUUID(),
      name: 'Magic Scroll',
      description: 'Contains powerful magic spells.',
      type: 'consumable',
      quantity: 3,
      equipped: false,
    },
    {
      id: crypto.randomUUID(),
      name: 'Ring of Invisibility',
      description: 'Grants temporary invisibility to the wearer.',
      type: 'accessory',
      quantity: 1,
      equipped: false,
    },
    {
      id: crypto.randomUUID(),
      name: 'Amulet of Wisdom',
      description: 'Enhances the wearer\'s intelligence and magical abilities.',
      type: 'accessory',
      quantity: 1,
      equipped: false,
    },
    {
      id: crypto.randomUUID(),
      name: 'Boots of Speed',
      description: 'Increases the wearer\'s movement speed.',
      type: 'armor',
      quantity: 1,
      equipped: false,  
    },
    {
      id: crypto.randomUUID(),
      name: 'Cloak of Shadows',
      description: 'Provides protection from detection and enhances stealth.',
      type: 'armor',
      quantity: 1,
      equipped: false,
    },
    {
      id: crypto.randomUUID(),
      name: 'Staff of Power',
      description: 'A powerful staff that can unleash devastating magical attacks.',
      type: 'weapon',
      quantity: 1,
      equipped: false,  
    },
    {
      id: crypto.randomUUID(),
      name: 'Helmet of Courage',
      description: 'A sturdy helmet that boosts the wearer\'s bravery and resilience.',
      type: 'armor',
      quantity: 1,
      equipped: false,
    },
    {
      id: crypto.randomUUID(),      name: 'Gloves of Dexterity',
      description: 'Enhances the wearer\'s agility and precision.',
      type: 'armor',
      quantity: 1,
      equipped: false,  
    },
    {
      id: crypto.randomUUID(),
      name: 'Belt of Strength',
      description: 'Increases the wearer\'s physical strength and endurance.',
      type: 'accessory',
      quantity: 1,
      equipped: false,  
    },
    {
      id: crypto.randomUUID(),
      name: 'Bracers of Defense',
      description: 'Provides additional protection to the wearer\'s arms.',
      type: 'armor',
      quantity: 1,
      equipped: false,  
    },
    {
      id: crypto.randomUUID(),
      name: 'Cape of Resilience',
      description: 'Grants the wearer increased resistance to damage.',
      type: 'armor',
      quantity: 1,
      equipped: false,  
    },
    {
      id: crypto.randomUUID(),
      name: 'Lantern of Guidance',
      description: 'Illuminates the path ahead and reveals hidden secrets.',
      type: 'accessory',
      quantity: 1,
      equipped: false, 
    }
  ];